name: Release Infrastructure as Code (IaC)

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      AWS_ACCESS_KEY_ID:
        description: 'AWS Access Key ID'
        required: true
        type: string
      AWS_SECRET_ACCESS_KEY:
        description: 'AWS Secret Access Key'
        required: true
        type: string
      AWS_SESSION_TOKEN:
        description: 'AWS Session Token (if applicable)'
        required: false
        type: string

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS credentials
      run: |
        echo "[default]" > ~/.aws/credentials
        echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
        echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
        echo "aws_session_token=${{ secrets.AWS_SESSION_TOKEN }}" >> ~/.aws/credentials

    - name: Change working directory to 'iac'
      run: cd iac

    - name: Terraform init
      run: terraform init
      working-directory: iac

    - name: Terraform plan
      run: terraform plan
      working-directory: iac

    - name: Terraform apply
      run: terraform apply --auto-approve
      working-directory: iac

    - name: Commit and push changes to the repository
      run: git push
      working-directory: iac
